name = "What a Mess"
default_targets = ["win32", "win64", "appimage"]
build_directory = "../makelove-build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-*.py",
    "-*.ttf",
    "-*/cringeboogaloo.wav",
    "-*/cringomat.wav",
    "-*/hypercringe.wav",
]

icon_file = "../icon.png"
