name = "What-a-Mess"
default_targets = ["win32", "win64", "appimage", "macos"]
build_directory = "../makelove-build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-*.py",
    "-*.ttf",
    "-*/cringeboogaloo.wav",
    "-*/cringomat.wav",
    "-*/hypercringe.wav",
    "-*/devmode",
]

icon_file = "../icon.png"

[archive_files]
"../README.md" = "README.md"
